import { context, getOctokit } from '@actions/github'
import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { runCommand } from './process.js'
import { type SnapshotDetails, studioUrl } from './studio.js'

const marker = '<!-- kubb-studio-snapshot -->'
type Pull = { head: { ref: string; repo?: { full_name?: string } | null } }

export async function updateComment(snapshot: SnapshotDetails, agentSlug: string, token: string): Promise<void> {
  if (!token || !context.issue.number) return
  const github = getOctokit(token)
  const { owner, repo } = context.repo
  const body = [
    marker,
    `### Kubb snapshot — ${snapshot.name}@${snapshot.version}`,
    '',
    `Expires ${snapshot.expiresAt ?? 'soon'}`,
    '',
    `[Install the snapshot](${snapshot.url})`,
    '',
    `Agent: ${studioUrl}/agents/${agentSlug}`,
  ].join('\n')
  const comments = await github.paginate(github.rest.issues.listComments, { owner, repo, issue_number: context.issue.number })
  const existing = comments.find((item: { body?: string }) => item.body?.includes(marker))
  if (existing) await github.rest.issues.updateComment({ owner, repo, comment_id: existing.id, body })
  else await github.rest.issues.createComment({ owner, repo, issue_number: context.issue.number, body })
}

export async function initConfig(token: string): Promise<boolean> {
  if (existsSync(join(process.cwd(), 'kubb.config.ts'))) return false
  const { owner, repo } = context.repo
  const defaultBranch = context.payload.repository?.default_branch ?? 'main'
  if (token) {
    const github = getOctokit(token)
    const pulls = await github.paginate(github.rest.pulls.list, { owner, repo, base: defaultBranch, state: 'open' })
    if (pulls.some((pull: Pull) => pull.head.repo?.full_name === `${owner}/${repo}` && pull.head.ref.startsWith('kubb/init-'))) return true
  }
  const branch = `kubb/init-${context.runId}`
  await runCommand('git', ['fetch', 'origin', defaultBranch])
  await runCommand('git', ['switch', '-c', branch, `origin/${defaultBranch}`])
  await runCommand('npx', ['kubb', 'init', '--yes'])
  await runCommand('git', ['config', 'user.name', 'github-actions[bot]'])
  await runCommand('git', ['config', 'user.email', '41898282+github-actions[bot]@users.noreply.github.com'])
  await runCommand('git', ['add', '-A'])
  await runCommand('git', ['commit', '-m', 'chore: initialize Kubb'])
  await runCommand('git', ['push', '--set-upstream', 'origin', branch])
  if (!token || !context.issue.number) return true
  const github = getOctokit(token)
  await github.rest.pulls.create({
    owner,
    repo,
    head: branch,
    base: defaultBranch,
    title: 'chore: initialize Kubb',
    body: 'Generated by the Kubb snapshot action.',
  })
  return true
}
