name: PR

on:
  pull_request:

permissions: {}

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: kubb-labs/config/.github/setup@ec40df0e3e54565e006f6d92a2fce16ff43b14d8 # main
        with:
          node-version: '22.22.3'
      - run: pnpm run format
      - run: pnpm run typecheck
      - run: pnpm run lint
      - run: pnpm test
      - run: pnpm run build

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: github.actor != 'github-actions[bot]'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: kubb-labs/config/.github/setup@ec40df0e3e54565e006f6d92a2fce16ff43b14d8 # main
        with:
          node-version: '22.22.3'
      - run: pnpm test --coverage
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        if: ${{ !cancelled() }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  dependency-diff:
    name: Dependency Diff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: github.actor != 'github-actions[bot]' && github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: e18e/action-dependency-diff@5d3c6ac2ad2de2eaca1dc120c5accfd9590764b6 # v1
        continue-on-error: true
        with:
          duplicate-threshold: 5
          size-threshold: -1

  compressed-size:
    name: Compressed size
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: github.actor != 'github-actions[bot]' && github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: kubb-labs/config/.github/setup@ec40df0e3e54565e006f6d92a2fce16ff43b14d8 # main
        with:
          node-version: '22.22.3'
      - uses: preactjs/compressed-size-action@66325aad6443cb7cf89c4bfcd414aea2367cda94 # v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          build-script: 'build'
          pattern: './dist/**/*.{js,mjs,cjs}'
